#################
#  tomcat 的web访问端口号
#
###################
server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size: 80KB


####################################################
## 连接池的配置
####################################################
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource   #数据源类型 HikariCP
    driver-class-name: com.mysql.jdbc.Driver   #mysql驱动
    url: jdbc:mysql://192.168.199.229/foodie-shop-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: 123456
    hikari:
      connection-timeout: 30000  # 等待连接池分配连接的最大时长 ms
      minimum-idle: 5  #最小连接数 5  连接池的最小容量
      maximum-pool-size: 20 #最大连接数
      auto-commit: true #自动提交
      idle-timeout: 600000  #连接超时最大时长 ms  10min
      pool-name: DateSourceHikariCP  #连接池的名称
      max-lifetime: 1800000  #连接的生命时长 ms,超时未使用则释放
      connection-test-query: SELECT 1 #连接时的测试语句
  servlet:
    multipart:
      max-file-size: 512000   # 文件上传大小 默认为1M ，我们改为500KB
      max-request-size: 512000 # 限制请求大小为500KB
####################################################
## mybatis的配置
####################################################
mybatis:
  type-aliases-package: com.wuyiccc.pojo  # 所有pojo类所在的包路径，取别名
  mapper-locations: classpath:mapper/*.xml  # mybatis的映射文件的位置---配置查询语句
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 在控制台输出日志的实现


##########
##  mybatis mapper配置
########
# 通用mapper配置
mapper:
  mappers: com.wuyiccc.my.mapper.MyMapper
  not-empty: false
  identity: MYSQL
# 分页插件配置
pagehelper:
  helper-dialect: mysql   # 数据库方言
  support-methods-arguments: true  # 是否支持分页的参数传参
